### ISSUE TITLE
overflow hidden to prevent horisontal scrolling

### ISSUE THREAD

**Issue by eklem** [eklem/life-index#12]
If words or single strings of text in search result items are longer than the width, the page will be able to scroll horisontal. Set

``` css
div {overflow:hidden;}
```
